defaults:
  ttl: 1800
  readonly: false
  urlencode: false
  c_threshold: 10000
  compression: true
  debug: true
  namespace: money
  sessions: true
  session_servers: false
  fragments: false
  memory: 64
  servers: localhost:11211
  benchmarking: true
  raise_errors: true
  fast_hash: false
  fastest_hash: false

development:
  sessions: false
  fragments: false
  raise_errors: true
  servers:
    - 127.0.0.1:11211

# turn off caching
test: 
  disabled: true

production:
  memory: 256
  benchmarking: false
  servers:
    - purple:11211
    - red:11211
